root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "CGO_ENABLED=0 go build -gcflags='-N -l' -o ./tmp/main ./cmd/app"
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", "testdata", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "gohtml", "templ", "html"]
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
